# Generated by Django 6.0.4 on 2026-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('warehouse', models.CharField(max_length=100)),
                ('product_variant', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
